### PR TITLE
Update ja Translation(v0.8.4) 

### PR DESCRIPTION
**Pull request by shg166**
After all this time, BOB has also translated the update history.

### CODE REVIEW

**Comment by algernon-A** [comment]
Also two more keys only just added for upcoming feature:
```
<Translation ID="BOB_OPT_WIR" String="Wires" />
<Translation ID="BOB_OPT_WTH" String="Thinner electrical wires" />
```

These are to do with making the game's electrical wires (power lines and railway catenaries) thinner and more realistic.

**Comment by shg166** [comment]
Is the thin wire setting fixed at "thinner"?
Or does the slider change the thinness?
The expression will change during translation.

**Comment by algernon-A** [comment]
Fixed at "thinner".

**Comment by shg166** [comment]
Thanks for the reply.
I'll make a pull request later.

**Pull request merged**
